name: My First GitHub Actions pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code on runner machine
      uses: actions/checkout@v4

    - name: Run random commands
      run: |
        ls -al
        whoami
        hostname
        pwd
        echo "End of the line" 
    
    - name: SSH to EC2 instance
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          whoami
          hostname
          echo "End of SSH Script on EC2"

    - name: SCP index.html to EC2 instance
      uses: actions/checkout@v4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: ./
        target: /home/ubuntu

    - name: Copy the files to nginx folder
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          sudo cp /home/ubuntu/* /var/www/html